In [1]:
import pandas as pd
from sklearn import linear_regression

ImportError: cannot import name 'linear_regression' from 'sklearn' (C:\Users\Tejashaarav S\anaconda3\lib\site-packages\sklearn\__init__.py)

In [2]:
import pandas as pd
from sklearn import linear_model

In [3]:
regr = linear_model.LinearRegression()

In [4]:
df = pd.DataFrame({'weight':[100,200,300,400,500,600],'vol':[10,20,30,40,50,60],'co2':[1,2,3,4,5,6]})


In [5]:
df

weight  vol  co2
0     100   10    1
1     200   20    2
2     300   30    3
3     400   40    4
4     500   50    5
5     600   60    6

In [8]:
x = df[['weight','vol']]
y = df['co2']


In [9]:
regr.fit(x,y)

LinearRegression()

In [12]:
predict = regr.predict([[3400,20]])
predict

array([33.68316832])

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [3]:
df = pd.read_csv("breast_cancer_data.csv")
df

Age        BMI  Glucose  Insulin      HOMA   Leptin  Adiponectin  \
0     48  23.500000       70    2.707  0.467409   8.8071     9.702400   
1     83  20.690495       92    3.115  0.706897   8.8438     5.429285   
2     82  23.124670       91    4.498  1.009651  17.9393    22.432040   
3     68  21.367521       77    3.226  0.612725   9.8827     7.169560   
4     86  21.111111       92    3.549  0.805386   6.6994     4.819240   
..   ...        ...      ...      ...       ...      ...          ...   
111   45  26.850000       92    3.330  0.755688  54.6800    12.100000   
112   62  26.840000      100    4.530  1.117400  12.4500    21.420000   
113   65  32.050000       97    5.730  1.370998  61.4800    22.540000   
114   72  25.590000       82    2.820  0.570392  24.9600    33.750000   
115   86  27.180000      138   19.910  6.777364  90.2800    14.110000   

     Resistin    MCP.1  Classification  
0     7.99585  417.114               1  
1     4.06405  468.786               1  
2     9.27715  554.697               1  
3    12.76600  928.220               1  
4    10.57635  773.920               1  
..        ...      ...             ...  
111  10.96000  268.230               2  
112   7.32000  330.160               2  
113  10.33000  314.050               2  
114   3.27000  392.460               2  
115   4.35000   90.090               2  

[116 rows x 10 columns]

In [4]:
df.columns

Index(['Age', 'BMI', 'Glucose', 'Insulin', 'HOMA', 'Leptin', 'Adiponectin',
       'Resistin', 'MCP.1', 'Classification'],
      dtype='object')

In [5]:
df.head()

Age        BMI  Glucose  Insulin      HOMA   Leptin  Adiponectin  Resistin  \
0   48  23.500000       70    2.707  0.467409   8.8071     9.702400   7.99585   
1   83  20.690495       92    3.115  0.706897   8.8438     5.429285   4.06405   
2   82  23.124670       91    4.498  1.009651  17.9393    22.432040   9.27715   
3   68  21.367521       77    3.226  0.612725   9.8827     7.169560  12.76600   
4   86  21.111111       92    3.549  0.805386   6.6994     4.819240  10.57635   

     MCP.1  Classification  
0  417.114               1  
1  468.786               1  
2  554.697               1  
3  928.220               1  
4  773.920               1

In [6]:
df.tail()

Age    BMI  Glucose  Insulin      HOMA  Leptin  Adiponectin  Resistin  \
111   45  26.85       92     3.33  0.755688   54.68        12.10     10.96   
112   62  26.84      100     4.53  1.117400   12.45        21.42      7.32   
113   65  32.05       97     5.73  1.370998   61.48        22.54     10.33   
114   72  25.59       82     2.82  0.570392   24.96        33.75      3.27   
115   86  27.18      138    19.91  6.777364   90.28        14.11      4.35   

      MCP.1  Classification  
111  268.23               2  
112  330.16               2  
113  314.05               2  
114  392.46               2  
115   90.09               2

In [7]:
df.info

<bound method DataFrame.info of      Age        BMI  Glucose  Insulin      HOMA   Leptin  Adiponectin  \
0     48  23.500000       70    2.707  0.467409   8.8071     9.702400   
1     83  20.690495       92    3.115  0.706897   8.8438     5.429285   
2     82  23.124670       91    4.498  1.009651  17.9393    22.432040   
3     68  21.367521       77    3.226  0.612725   9.8827     7.169560   
4     86  21.111111       92    3.549  0.805386   6.6994     4.819240   
..   ...        ...      ...      ...       ...      ...          ...   
111   45  26.850000       92    3.330  0.755688  54.6800    12.100000   
112   62  26.840000      100    4.530  1.117400  12.4500    21.420000   
113   65  32.050000       97    5.730  1.370998  61.4800    22.540000   
114   72  25.590000       82    2.820  0.570392  24.9600    33.750000   
115   86  27.180000      138   19.910  6.777364  90.2800    14.110000   

     Resistin    MCP.1  Classification  
0     7.99585  417.114               1  
1     4.0

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 116 entries, 0 to 115
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Age             116 non-null    int64  
 1   BMI             116 non-null    float64
 2   Glucose         116 non-null    int64  
 3   Insulin         116 non-null    float64
 4   HOMA            116 non-null    float64
 5   Leptin          116 non-null    float64
 6   Adiponectin     116 non-null    float64
 7   Resistin        116 non-null    float64
 8   MCP.1           116 non-null    float64
 9   Classification  116 non-null    int64  
dtypes: float64(7), int64(3)
memory usage: 9.2 KB


In [9]:
df.describe()

Age         BMI     Glucose     Insulin        HOMA      Leptin  \
count  116.000000  116.000000  116.000000  116.000000  116.000000  116.000000   
mean    57.301724   27.582111   97.793103   10.012086    2.694988   26.615080   
std     16.112766    5.020136   22.525162   10.067768    3.642043   19.183294   
min     24.000000   18.370000   60.000000    2.432000    0.467409    4.311000   
25%     45.000000   22.973205   85.750000    4.359250    0.917966   12.313675   
50%     56.000000   27.662416   92.000000    5.924500    1.380939   20.271000   
75%     71.000000   31.241442  102.000000   11.189250    2.857787   37.378300   
max     89.000000   38.578759  201.000000   58.460000   25.050342   90.280000   

       Adiponectin    Resistin        MCP.1  Classification  
count   116.000000  116.000000   116.000000      116.000000  
mean     10.180874   14.725966   534.647000        1.551724  
std       6.843341   12.390646   345.912663        0.499475  
min       1.656020    3.210000    45.843000        1.000000  
25%       5.474283    6.881763   269.978250        1.000000  
50%       8.352692   10.827740   471.322500        2.000000  
75%      11.815970   17.755207   700.085000        2.000000  
max      38.040000   82.100000  1698.440000        2.000000

In [11]:
df.isnull().sum()

Age               0
BMI               0
Glucose           0
Insulin           0
HOMA              0
Leptin            0
Adiponectin       0
Resistin          0
MCP.1             0
Classification    0
dtype: int64

In [12]:
df.corr()

Age       BMI   Glucose   Insulin      HOMA    Leptin  \
Age             1.000000  0.008530  0.230106  0.032495  0.127033  0.102626   
BMI             0.008530  1.000000  0.138845  0.145295  0.114480  0.569593   
Glucose         0.230106  0.138845  1.000000  0.504653  0.696212  0.305080   
Insulin         0.032495  0.145295  0.504653  1.000000  0.932198  0.301462   
HOMA            0.127033  0.114480  0.696212  0.932198  1.000000  0.327210   
Leptin          0.102626  0.569593  0.305080  0.301462  0.327210  1.000000   
Adiponectin    -0.219813 -0.302735 -0.122121 -0.031296 -0.056337 -0.095389   
Resistin        0.002742  0.195350  0.291327  0.146731  0.231101  0.256234   
MCP.1           0.013462  0.224038  0.264879  0.174356  0.259529  0.014009   
Classification -0.043555 -0.132586  0.384315  0.276804  0.284012 -0.001078   

                Adiponectin  Resistin     MCP.1  Classification  
Age               -0.219813  0.002742  0.013462       -0.043555  
BMI               -0.302735  0.195350  0.224038       -0.132586  
Glucose           -0.122121  0.291327  0.264879        0.384315  
Insulin           -0.031296  0.146731  0.174356        0.276804  
HOMA              -0.056337  0.231101  0.259529        0.284012  
Leptin            -0.095389  0.256234  0.014009       -0.001078  
Adiponectin        1.000000 -0.252363 -0.200694       -0.019490  
Resistin          -0.252363  1.000000  0.366474        0.227310  
MCP.1             -0.200694  0.366474  1.000000        0.091381  
Classification    -0.019490  0.227310  0.091381        1.000000

In [13]:
from scipy.stats import zscore

In [14]:
z = np.abs(zscore(df))
z

array([[0.57979363, 0.81667527, 1.23922225, ..., 0.54551749, 0.34125061,
        1.10940039],
       [1.60182096, 1.37875056, 0.25829943, ..., 0.86421418, 0.1912238 ,
        1.10940039],
       [1.53948912, 0.89176446, 0.30288683, ..., 0.4416602 , 0.05821407,
        1.10940039],
       ...,
       [0.47984774, 0.89385486, 0.03536242, ..., 0.3563202 , 0.64049127,
        0.90138782],
       [0.91617066, 0.39854568, 0.70417344, ..., 0.92857684, 0.41283214,
        0.90138782],
       [1.7888165 , 0.0804471 , 1.79272102, ..., 0.84103616, 1.29074683,
        0.90138782]])

In [15]:
data =df[(z<3).all(axis=1)]
data

Age        BMI  Glucose  Insulin      HOMA   Leptin  Adiponectin  \
0     48  23.500000       70    2.707  0.467409   8.8071     9.702400   
1     83  20.690495       92    3.115  0.706897   8.8438     5.429285   
2     82  23.124670       91    4.498  1.009651  17.9393    22.432040   
3     68  21.367521       77    3.226  0.612725   9.8827     7.169560   
4     86  21.111111       92    3.549  0.805386   6.6994     4.819240   
..   ...        ...      ...      ...       ...      ...          ...   
108   68  35.560000      131    8.150  2.633537  17.8700    11.900000   
109   75  30.480000      152    7.010  2.628283  50.5300    10.060000   
111   45  26.850000       92    3.330  0.755688  54.6800    12.100000   
112   62  26.840000      100    4.530  1.117400  12.4500    21.420000   
113   65  32.050000       97    5.730  1.370998  61.4800    22.540000   

     Resistin    MCP.1  Classification  
0     7.99585  417.114               1  
1     4.06405  468.786               1  
2     9.27715  554.697               1  
3    12.76600  928.220               1  
4    10.57635  773.920               1  
..        ...      ...             ...  
108   4.19000  198.400               2  
109  11.73000   99.450               2  
111  10.96000  268.230               2  
112   7.32000  330.160               2  
113  10.33000  314.050               2  

[102 rows x 10 columns]

In [16]:
x = data.drop('Classification',axis =1)
y = data['Classification']

In [17]:
x

Age        BMI  Glucose  Insulin      HOMA   Leptin  Adiponectin  \
0     48  23.500000       70    2.707  0.467409   8.8071     9.702400   
1     83  20.690495       92    3.115  0.706897   8.8438     5.429285   
2     82  23.124670       91    4.498  1.009651  17.9393    22.432040   
3     68  21.367521       77    3.226  0.612725   9.8827     7.169560   
4     86  21.111111       92    3.549  0.805386   6.6994     4.819240   
..   ...        ...      ...      ...       ...      ...          ...   
108   68  35.560000      131    8.150  2.633537  17.8700    11.900000   
109   75  30.480000      152    7.010  2.628283  50.5300    10.060000   
111   45  26.850000       92    3.330  0.755688  54.6800    12.100000   
112   62  26.840000      100    4.530  1.117400  12.4500    21.420000   
113   65  32.050000       97    5.730  1.370998  61.4800    22.540000   

     Resistin    MCP.1  
0     7.99585  417.114  
1     4.06405  468.786  
2     9.27715  554.697  
3    12.76600  928.220  
4    10.57635  773.920  
..        ...      ...  
108   4.19000  198.400  
109  11.73000   99.450  
111  10.96000  268.230  
112   7.32000  330.160  
113  10.33000  314.050  

[102 rows x 9 columns]

In [18]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()

In [19]:
x = ss.fit_transform(x)
x

array([[-5.90224376e-01, -7.93217563e-01, -1.63140597e+00,
        -8.51553112e-01, -8.78745379e-01, -9.69784751e-01,
         1.62442393e-02, -6.19900680e-01, -2.94961563e-01],
       [ 1.64899031e+00, -1.34812194e+00, -1.60584356e-01,
        -7.93335867e-01, -7.49405777e-01, -9.67551183e-01,
        -7.48759370e-01, -1.07828206e+00, -9.78809306e-02],
       [ 1.58501275e+00, -8.67348779e-01, -2.27439884e-01,
        -5.95996529e-01, -5.85898884e-01, -4.13997462e-01,
         2.29519544e+00, -4.70522770e-01,  2.29789649e-01],
       [ 6.89326875e-01, -1.21440263e+00, -1.16341727e+00,
        -7.77497352e-01, -8.00265055e-01, -9.04323547e-01,
        -4.37202893e-01, -6.37818644e-02,  1.65443257e+00],
       [ 1.84092300e+00, -1.26504612e+00, -1.60584356e-01,
        -7.31408700e-01, -6.96215215e-01, -1.09805974e+00,
        -8.57973989e-01, -3.19058023e-01,  1.06592155e+00],
       [-5.26246813e-01, -9.20718385e-01, -1.60584356e-01,
        -7.77497352e-01, -7.35801739e-01, -1.090007

In [20]:
from sklearn.model_selection import train_test_split


In [23]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,random_state = 50,test_size = 0.2)

In [22]:
xtrain

array([[-9.74089751e-01, -1.21590504e+00, -9.37288281e-02,
        -8.09887829e-01, -7.59627455e-01, -3.44416024e-01,
        -2.05657230e-01,  4.73683658e-01, -6.58041969e-01],
       [-2.06359001e-01,  5.86023397e-01, -2.94295411e-01,
        -4.47742319e-01, -4.67320485e-01, -7.55319581e-01,
         2.14324461e-02, -3.63751315e-01,  2.79747125e+00],
       [-3.98291688e-01, -1.80644196e+00,  7.08537505e-01,
        -3.77396481e-01, -2.87718412e-01, -9.20311515e-01,
         5.63637660e-01, -1.17784985e+00,  7.32716526e-02],
       [ 1.32910250e+00, -4.37700230e-01, -2.29996124e+00,
        -7.37258962e-01, -8.50783300e-01, -1.10210086e+00,
         1.71083928e-01, -1.00836136e+00, -1.08586622e+00],
       [ 1.13716981e+00,  5.85399650e-01,  3.85074731e+00,
        -2.37560941e-01,  2.88268448e-01,  1.56947824e+00,
         8.02643489e-02, -1.84561943e-01, -1.50655434e+00],
       [ 2.41483937e-01,  8.93309137e-01, -6.28573050e-01,
         1.34158183e+00,  9.15750026e-01,  3.670576

In [25]:
ytest.shape

(21,)

In [26]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier

In [46]:
#logistic regression 
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

lr = LogisticRegression()
lr = lr.fit(xtrain,ytrain)
ytest_lr = lr.predict(xtest)
print("accuracy:",accuracy_score(ytest,ytest_lr) )

print("Classification Report:",classification_report(ytest_lr,ytest) )

accuracy: 0.7619047619047619
Classification Report:               precision    recall  f1-score   support

           1       0.89      0.67      0.76        12
           2       0.67      0.89      0.76         9

    accuracy                           0.76        21
   macro avg       0.78      0.78      0.76        21
weighted avg       0.79      0.76      0.76        21



In [45]:
#RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report


rf = RandomForestClassifier()
rf = rf.fit(xtrain,ytrain)
ytest_rf = rf.predict(xtest)
print("accuracy:",accuracy_score(ytest,ytest_rf) )

print("Classification Report:",classification_report(ytest_rf,ytest) )

accuracy: 0.6190476190476191
Classification Report:               precision    recall  f1-score   support

           1       0.56      0.56      0.56         9
           2       0.67      0.67      0.67        12

    accuracy                           0.62        21
   macro avg       0.61      0.61      0.61        21
weighted avg       0.62      0.62      0.62        21



In [47]:
#SVC
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

svc = SVC()
svc = svc.fit(xtrain,ytrain)
ytest_svc = svc.predict(xtest)
print("accuracy:",accuracy_score(ytest,ytest_svc) )

print("Classification Report:",classification_report(ytest_svc,ytest) )

accuracy: 0.8095238095238095
Classification Report:               precision    recall  f1-score   support

           1       0.89      0.73      0.80        11
           2       0.75      0.90      0.82        10

    accuracy                           0.81        21
   macro avg       0.82      0.81      0.81        21
weighted avg       0.82      0.81      0.81        21



In [44]:
#DecisionTreeClassifier

from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

dtc = DecisionTreeClassifier()
dtc = dtc.fit(xtrain,ytrain)
ytest_dtc = dtc.predict(xtest)
print("accuracy:",accuracy_score(ytest,ytest_dtc) )

print("Classification Report:",classification_report(ytest_dtc,ytest) )


accuracy: 0.7619047619047619
Classification Report:               precision    recall  f1-score   support

           1       0.56      0.83      0.67         6
           2       0.92      0.73      0.81        15

    accuracy                           0.76        21
   macro avg       0.74      0.78      0.74        21
weighted avg       0.81      0.76      0.77        21



In [48]:
#KNeighborsClassifier

from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

knc = KNeighborsClassifier()
knc = knc.fit(xtrain,ytrain)
ytest_knc = knc.predict(xtest)
print("accuracy:",accuracy_score(ytest,ytest_knc) )

print("Classification Report:",classification_report(ytest_knc,ytest) )


accuracy: 0.8095238095238095
Classification Report:               precision    recall  f1-score   support

           1       0.78      0.78      0.78         9
           2       0.83      0.83      0.83        12

    accuracy                           0.81        21
   macro avg       0.81      0.81      0.81        21
weighted avg       0.81      0.81      0.81        21



In [49]:
from sklearn.metrics import confusion_matrix

print("Confusion matrix:",confusion_matrix(ytest_knc,ytest) )

Confusion matrix: [[ 7  2]
 [ 2 10]]


1

75